export const siteConfig = {
  title: "Change Makers of the World",
  description:
    "A youth-led organization supporting girls' education, youth empowerment, and human rights in Afghanistan.",
  url: "https://cmworld.org",
  keywords: [
    "Change Makers of the World",
    "Change Makers",
    "Afghanistan",
    "Girls' Education",
    "Afghan Children",
    "Human Rights",
    "Afghan Youth",
    "Volunteer",
    "Education",
    "Taliban",
    "Global",
    "Community",
    "Nonprofit",
    "Non-governmental organization",
    "NGO",
    "Afghanistan",
    "Afghan Children",
    "Afghan Youth",
  ],
};
